name: build

on: [push]

jobs:
  build-executable:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: "${{ matrix.os }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Uv with Python and Nox
        uses: ./.github/actions/setup-uv-nox

      - name: Build executables
        run: uv run nox -s build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "dist-${{ matrix.os }}"
          path: dist/

  build-executable-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Uv with Python and Nox
        uses: ./.github/actions/setup-uv-nox

      - name: Build executables
        run: uv run nox -s build_linux

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-ubuntu-latest
          path: dist/
